### ISSUE TITLE
Couple of bugs I've found so far

### ISSUE THREAD

**Issue by ndv400** [Johnanater/AntiAdminAbuse#4]
1. When someone disables vanish, the plugin doesn't provide a translation for that action: 
![image](https://user-images.githubusercontent.com/1404955/62281195-ff4d8100-b455-11e9-8024-c76c12c2ce1d.png)
2. When someone disables godmode, the plugin still says that they've enabled it:
![image](https://user-images.githubusercontent.com/1404955/62281305-33c13d00-b456-11e9-907f-c878615ecfe9.png)
3. Still possible to kill players and damage structures in godmode. Works as intended in vanishmode, though.

**Comment by Johnanater** [comment]
Are you using a custom god mode plugin?

Edit: Fixed issue 1, looks like a good ol' copy paste error

**Comment by ndv400** [comment]
You're correct, my /god command has been automatically replaced by com.avirockets.unturned.lib.GoddCommand (which installs itself automatically if you use Avi's plugins. His plugins used to be on Imperial but now they're gone for some reason.) It also adds a /godd command. 
The permission for it is avi.cmd.god, here's the lib.
[AviRockets.Unturned.Addon.dll.zip](https://github.com/Johnanater/AntiAdminAbuse/files/3460264/AviRockets.Unturned.Addon.dll.zip)

**Comment by Johnanater** [comment]
I'd just use the default Rocket /god command for now.

**Comment by Johnanater** [comment]
Closing.
