### ISSUE TITLE
replace command.Equals with command.Contains 

### ISSUE THREAD

**Issue by ndv400** [Johnanater/AntiAdminAbuse#5]
and this is why:
![image](https://user-images.githubusercontent.com/1404955/80629172-21af1200-8a5b-11ea-9ff6-a30df66fc2e6.png)
so yeah could you please do that?

**Comment by Johnanater** [comment]
I don't know how I missed this, I'll fix that

**Comment by Johnanater** [comment]
Fixed in:
https://github.com/Johnanater/AntiAdminAbuse/releases/tag/1.0.2
